name: Build on Tag

on:
  push:
    tags: '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout kernel source
      uses: actions/checkout@v4
      with:
        submodules: true
    
    - name: Unshallow submodules
      shell: bash
      run: /usr/bin/git submodule foreach /usr/bin/git fetch --unshallow

    - name: Patch KernelSU version detection
      shell: bash
      run: /usr/bin/sed -i 's/KSU_GIT_VERSION := $(shell cd $(srctree)\/$(src); \/usr\/bin\/env PATH="$$PATH":\/usr\/bin:\/usr\/local\/bin git rev-list --count HEAD)/KSU_GIT_VERSION := 1638/g' KernelSU/kernel/Makefile

    - name: Checkout zipper
      uses: actions/checkout@v4
      with:
        repository: Builds-Feas/AnyKernel3
        ref: merlinx-lineage
        path: zipper

    - name: Android kernel build
      uses: lemniskett/android-kernel-actions@master
      id: build
      env:
        NAME: merlinx-ksu-lineage-20
      with:
        arch: arm64
        compiler: aosp-clang/llvm-r416183/clang-r416183
        defconfig: merlin_defconfig
        image: Image

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: merlinx-ksu-lineage-20
        retention-days: 7
        path: |
          /github/workspace/zipper/*.zip
          /home/runner/work/android_kernel_xiaomi_mt6768/android_kernel_xiaomi_mt6768/zipper/*.zip

    - name: Release build
      uses: ncipollo/release-action@v1
      with:
        artifacts: "${{ steps.build.outputs.outfile }},/github/workspace/zipper/*.zip,/home/runner/work/android_kernel_xiaomi_mt6768/android_kernel_xiaomi_mt6768/zipper/*.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
